# -*- coding: utf-8 -*-
"""usingdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Xz_rbYpOi4XOTX2V2CWPgTHAPE6eF6N
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from keras.models import load_model

# data = pd.read_excel('/content/drive/My Drive/highlight/data/nhdata/20200428_Faker_604867381.mp4_3.xlsx')
# model = load_model('/content/drive/My Drive/highlight/송호성의 방/hl/highlight2.h5')

# data

def delta(data, data_path):
    # print(data.columns)
    # print(data.index)
    df = data
    # df = pd.DataFrame(index=data['time'])
    df['dk'] = pd.Series()
    df['dd'] = pd.Series()
    df['da'] = pd.Series()

    df[1] = pd.Series()
    df[2] = pd.Series()
    df[3] = pd.Series()
    df[4] = pd.Series()
    df[5] = pd.Series()
    df[6] = pd.Series()
    df[7] = pd.Series()
    df[8] = pd.Series()

    for i in range(1, len(df)):
        df['dk'][i] = data['k'][i] - data['k'][i-1]
        df['dd'][i] = data['d'][i] - data['d'][i-1]
        df['da'][i] = data['a'][i] - data['a'][i-1]

        df[1][i] = abs(data['ha'][i] - data['ha'][i-1])
        df[2][i] = abs(data['sa'][i] - data['sa'][i-1])
        df[3][i] = abs(data['an'][i] - data['an'][i-1])
        df[4][i] = abs(data['ca'][i] - data['ca'][i-1])
        df[5][i] = abs(data['dis'][i] - data['dis'][i-1])
        df[6][i] = abs(data['fe'][i] - data['fe'][i-1])
        df[7][i] = abs(data['sup'][i] - data['sup'][i-1])
        df[8][i] = abs(data['conf'][i] - data['conf'][i-1])

    df['demo'] = df.iloc[:,3:11].sum(axis=1)
    df.dropna(inplace=True)

    df.to_csv(data_path, +'/kda.csv')

    return df, df['dk'],df['dd'],df['da']

# all,k,d,a = delta(data)

# plt.figure(figsize=(20, 9))
# # plt.plot(all)
# plt.plot(k)
# plt.plot(d)
# plt.plot(a)
# # plt.plot(data['count']/max(data['count']))
# # plt.plot(df['demo']/max(df['demo']))
# # plt.plot(data['sound']/max(data['sound']))
# plt.show()
# plt.close()

# k

# d

# a

# all

